### ISSUE TITLE
ChunkedIO Api is Incompatible with Zip::File.open_buffer

### ISSUE THREAD

**Issue by Antsiscool** [janko/down#26]
I am archiving a zip file uploaded with Shrine to S3. Zip::File is complaining about ChunkedIO saying that is not implementing an IO-like object. 

The error is:
```
RuntimeError: Zip::File.open_buffer expects a String or IO-like argument (responds to tell, seek, read, close). Found: Down::ChunkedIO
``` 

It looks like ChunkedIO is not implementing tell or seek.

I have worked around this problem by calling ```download``` instead of ```open``` on the Shrine object.

**Comment by janko** [comment]
Thanks for reporting. It would be possible to add `#tell` and `#seek` to `Down::ChunkedIO`, but I first want to check with you whether you think there are advantages of using `Down::ChunkedIO` for zipping, instead a file on disk.

**Comment by janko** [comment]
I suppose the benefit might be performance, because you'd be able to zip the file while you're downloading it. I already started working on this.
