### ISSUE TITLE
4.8.2 release?

### ISSUE THREAD

**Issue by timdiggins** [janko/down#33]
Just noting that almost everything in the repo seems to suggest that 4.8.2 is the latest release, but in fact rubygems only has 4.8.1 (https://rubygems.org/gems/down/).

**Comment by janko** [comment]
Yes, I released 4.8.2 with attempted fix for https://github.com/janko/down/issues/32, but quickly yanked it when I found a potentially severe bug in the latest changes.

I will eventually get back to finishing that, but in the meantime I agree master should be “reverted” to 4.8.1.
