### ISSUE TITLE
Can't get it working with Rails 5.2

### ISSUE THREAD

**Issue by thiagodiniz** [janko/down#34]
I have installed the gem through the Gemfile, but when tried to use it at the console it didn't worked:

```ruby
irb(main):004:0> Down.download("https://example.org/410897162341.pdf")
Traceback (most recent call last):
        2: from (irb):4
        1: from (irb):4:in `rescue in irb_binding'
NameError (uninitialized constant Down)
```
```ruby
irb(main):002:0> require 'down'
Traceback (most recent call last):
        2: from (irb):2
        1: from (irb):2:in `rescue in irb_binding'
LoadError (cannot load such file -- down)
```

**Comment by janko** [comment]
It seems that the `down` gem you added for some reason isn't detected by the Rails console, as `require "down"` should definitely work. My only guess is that you're using Spring and that it somehow hasn't detected the Gemfile change. I'm closing as it's definitely not a problem with Down.

**Comment by thiagodiniz** [comment]
thanks, @janko. You were right, that was spring messing with the loading. 
Sorry to bother with this issue.
