### ISSUE TITLE
Ruby 2.7+ deprecation warning

### ISSUE THREAD

**Issue by smileart** [janko/down#38]
Hey there! Trying to use this brilliant gem with Ruby 2.7 

```ruby
…
    tempfile = Down.download(
      link,
      content_length_proc: -> (content_length) {
        file_size = content_length
      },
      progress_proc: -> (progress) {
        changed
        downloaded_size = progress
        notify_observers(file_size, downloaded_size)
      }
    )
…
```

and getting the following warnings:

````shell
/usr/local/Cellar/rbenv/1.1.2/versions/2.7.0/lib/ruby/gems/2.7.0/gems/down-5.1.0/lib/down.rb:10: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/Cellar/rbenv/1.1.2/versions/2.7.0/lib/ruby/gems/2.7.0/gems/down-5.1.0/lib/down/backend.rb:12: warning: The called method `download' is defined here
````

It seems that some changes should be made for the [future versions](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) of Ruby.

Current workaround (just to hide the warnings, if someone  needs it right now):

```shell
RUBYOPT='-W:no-deprecated -W:no-experimental' <RUBY_COMMAND>
```

or adding this ENV variable to your shell init script.

Thanks for the lib.

**Comment by janko** [comment]
Thanks for reporting, I seem to have missed those when fixing keyword argument warnings before.
