### ISSUE TITLE
rename filename when download

### ISSUE THREAD

**Issue by Lupeipei** [janko/down#40]
Hi, thanks for this awesome gem, love it!
I have just had a problem that we wanted to rename the file after downloading, but I haven't found any way to solve it.
Is it possible that we can set the original_filename when using `download` class method, such as `Down.download(url, original_filename: 'hello.jpg')`
Appreciate a lot for your reply.

**Comment by Lupeipei** [comment]
Uh, forget it. I have found a solution.

**Comment by marselmustafin** [comment]
@Lupeipei could you please share your solution?

**Comment by loganh0522** [comment]
+1

**Comment by amitpatelx** [comment]
How to keep original file name?
