### ISSUE TITLE
Crash due to non existing HTTP error code

### ISSUE THREAD

**Issue by darndt** [janko/down#41]
While using the `Down::NetHttp` backend and downloading a file with an unusual response error code like 522 it crashes due to a KeyNotFound error caused by this line

https://github.com/janko/down/blob/11181e5205bd537d6389f6a1c2096768edb7f48b/lib/down/net_http.rb#L301

because 522 is not in the list of error codes `CODE_TO_OBJ` in the HTTPResponse class

https://www.rubydoc.info/stdlib/net/Net/HTTPResponse

Not sure what would be the best way to fix this.  In my project I'm just catching the KeyNotFound error...

**Comment by janko** [comment]
Thanks for the report. Yeah, we should definitely handle this in Down somehow. Would you like to take a stab at a pull request?

**Comment by jrochkind** [comment]
The class-per-status-code design makes this a bit tricky, en? Perhaps un
unrecognized 5xx should be turned into the class for a 500, unrecognize 4xx
a 400, etc?  Those are kind of the 'generic' versions. Although one would
hope to still be able to get back the actual response code too.

**Comment by jrochkind** [comment]
Or wait, what does the underlying net-http/open-url do, actually, when used
directly?

**Comment by darndt** [comment]
Proposed fix: #42

**Comment by janko** [comment]
https://github.com/janko/down/pull/42 has been merged.
