### ISSUE TITLE
Tempfile returned as nil

### ISSUE THREAD

**Issue by amitpatelx** [janko/down#47]
I am using `down (5.2.0)` with `Rails 5.x` and able to download file successfully but the problem is the filename gets changed so I am trying to rename the tempfile but it returns `nil`

```
pry> tempfile = Down.download('https://findkollegie.dk/wp-content/uploads/2018/04/knap-FK-300x54.png', destination: '/home/amit')
=> nil
> tempfile.path

NoMethodError:
       undefined method `path' for nil:NilClass

```

As per the [doc](https://github.com/janko/down#destination) this is expected behaviour but shouldn't it have consistent behaviour?

**Comment by janko** [comment]
If you're using downloading to a `:destination`, why do you need Down to open the file for you? I think it's better that you open it yourself if you need to. Otherwise you have to remember to close it (this won't happen automatically, as it wouldn't a Tempfile but a File).

**Comment by janko** [comment]
I'm closing this, as changing Down to return an opened file now would be a backwards incompatible change, as it would leak file descriptors for users not handling it.
