### ISSUE TITLE
Windows - FileUtils.mv Rename not allowed on an open file.

### ISSUE THREAD

**Issue by timothyeckert** [janko/down#49]
For some reason it looks like on the FileUtils.mv ruby is being denied the ability to rename the file.

Down::NotFound: Permission denied @ rb_file_s_rename - (C:/Users/vagrant/AppData/Local/Temp/open-uri20200930-1076-18a2wmi, C:/Users/vagrant/AppData/Local/Temp/down20200930-1076-19i1bix.pem)

```ruby
    open_uri_file = downloaded_file
    downloaded_file = copy_to_tempfile(URI(url).path, open_uri_file)
    OpenURI::Meta.init downloaded_file, open_uri_file

    downloaded_file.extend DownloadedFile
    downloaded_file
  rescue => error
    raise if error.is_a?(Down::Error)
    raise Down::NotFound, error.message
  end

  def copy_to_tempfile(basename, io)
    tempfile = Tempfile.new(['down', File.extname(basename)], binmode: true)
    if io.is_a?(OpenURI::Meta) && io.is_a?(Tempfile)
      FileUtils.mv io.path, tempfile.path
    else
      IO.copy_stream(io, tempfile.path)
      io.rewind
    end
    tempfile.open
    tempfile
  end
```

**Comment by janko** [comment]
Are you using the latest Down version? It should fix the issue: https://github.com/janko/down/blob/3a70e3590132a5a4842a8fb873c7758e5a471698/lib/down/net_http.rb#L182-L197

**Comment by timothyeckert** [comment]
I should have checked that, I assumed the version I grabbed from google was current but it wasn't, it was 1.1. I am upgrading to 5+ and will let you know. 

Sorry about that!

**Comment by timothyeckert** [comment]
This fixed my issue. 

Thanks for the quick response.
