### ISSUE TITLE
arg with destination return a path?

### ISSUE THREAD

**Issue by Guoxweii** [janko/down#53]
can arg with destination return a path?

**Comment by janko** [comment]
Yes, the `:destination` option requires a path to be passed in.

**Comment by Guoxweii** [comment]
l mean when call download with the arg : destination, the result now is nil,

can it return a value like path?

**Comment by janko** [comment]
It can, but what would be the advantage, given that you already have access to the path?

**Comment by Guoxweii** [comment]
the file name changed。。
