### ISSUE TITLE
undefined method `max_size=' when using Down.backend :http

### ISSUE THREAD

**Issue by infiton** [janko/down#61]
Using the `http` backend is not working with `max_size` option:

```
#Gemfile.lock
down (5.2.2)
http (5.0.1)
```

to reproduce:

```
Down.backend :http
remote_file = Down.open(src, max_size: 5 * 1024 * 1024)
remote_file.each_chunk do |chunk|
  # do something
end
```

**Comment by janko** [comment]
Only `Down.download` supports the `:max_size` option, because there you otherwise wouldn't have control over how much file you download. With `Down.open` you would have to implement this functionality yourself:

```rb
max_size = 5 * 1024 * 1024
remote_file = Down.open(src)

if remote_file.headers["Content-Length"]&.to_i >= max_size
  raise "request too large"
end
downloaded = 0

remote_file.each_chunk do |chunk|
  downloaded += chunk.bytesize
  if downloaded.bytesize >= max_size
    raise "request too large"
  end

  # do something
end
```

It would *probably* be possible to add `:max_size` support to `Down.open`, but it would be tricky to implement, I think.

**Comment by infiton** [comment]
interesting! With the default backend the code above works. With the default backend is `open(src, max_size: 5 * 1024 * 1024)` and then doing chunks only applying the `max_size` to size of the chunks?

At any rate, I think the api for `open` should be the same regardless of backend

**Comment by janko** [comment]
I think that on the default net/http backend the `:max_size` option is just ignored.

**Comment by janko** [comment]
I would gladly accept a pull request for this, but I don't have the capacity to work on this myself, so I'm closing this.
