### ISSUE TITLE
Error: Down::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate))

### ISSUE THREAD

**Issue by thanhtoan1196** [janko/down#66]
How to fix this error:
```
Down::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate))
```

**Comment by rafbm** [comment]
This is not an issue with Down. It is simply the error you will get whenever you request a URL that serves a certificate missing some intermediate certificate in its chain.

Other possible `SSLError` messages include “certificate has expired” or “unspecified certificate verification error”, for instance this case that serves no certificate at all:

```ruby
Down.download('https://neverssl.com/')
# => Down::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error))
```

**Comment by thanhtoan1196** [comment]
@rafbm I got it, thank you.
