### ISSUE TITLE
308 Permanent Redirect

### ISSUE THREAD

**Issue by jules-w2** [janko/down#72]
Hey 👋

Down isn't able to download files with 308 redirects.

Exemple : 
https://fakeimg.pl/1920x1280/fafbfc redirects to http://fakeimg.pl/1920x1280/fafbfc/  with an 308 code and them redirects to https://fakeimg.pl/1920x1280/fafbfc/ with a 301.

We can follow the redirects here : https://wheregoes.com/trace/20222494475/

Down::NetHttp.download("https://fakeimg.pl/1920x1280/fafbfc", :destination => "/Users/jules/Desktop/test.jpg", :max_redirects => 5)

308 Permanent Redirect

Have you any ideas ?

Bests

**Comment by janko** [comment]
It seems that open-uri [doesn't support 308 redirects](https://github.com/ruby/ruby/blob/a85cdb5a6e7d735b03eb5ae80e5ac0c5424eb259/lib/open-uri.rb#L353-L356), so by extension `Down::NetHttp` doesn't support it as well. You might want to use `Down::Http` instead, which I believe supports all 3xx redirects.

**Comment by woto** [comment]
Damn. Met the same problem while figuring out with same problem in shrine gem.

Does not work:

```ruby
Down.download(
  "https://www.react-spring.io/share.jpg",
  max_redirects: 2
)
```

Works:

```ruby
Down.open(
  "https://www.react-spring.io/share.jpg",
  max_redirects: 2
)
```
And seems (if I understand sources correctly) that is the problem why image from example does not downloads here: https://github.com/shrinerb/shrine/blob/master/lib/shrine/plugins/remote_url.rb#L19

temporarily replaced with `open` fixed problem.

```ruby
  plugin :remote_url,
  ...
         downloader: lambda { |url, **options|
           Down.open(url, **options)
         }
```

**Comment by woto** [comment]
Oh I was wrong, it fixes one error and brings other :)
