### ISSUE TITLE
Content-Disposition handling with non-standard header from IIS 10.0 returns `;` as part of filename

### ISSUE THREAD

**Issue by azrazalea-debtbook** [janko/down#78]
We ran into this issue out in the wild.

Downloading from https://emma.msrb.org/ER886357.pdf, the Content-Disposition header is set to:

"inline; filename=ER886357.pdf; creation-date=9/17/2012 1:51:37 PM; modification-date=9/17/2012 1:51:37 PM; size=3718678"

Using the method `original_filename` from https://github.com/janko/down/blob/master/lib/down/net_http.rb#L382 parses the filename from the header using https://github.com/janko/down/blob/master/lib/down/utils.rb#L14. Unfortunately since the triggering regex (the third one) uses "Not whitespace" as the matcher, it includes the `;` at the end of the filename field as part of the returned filename.

Currently in our project, we are working around this by `chomp`ing the ';' off the filename after having it returned.

Researching the header on MDN and the like, it looks like doing "Not ;" as the regex: `content_disposition[/filename=([^;]+)/, 1]` might work. It works for this specific use case, but I'm not sure if it'll work overall.

I'm happy to make a pull request if we can figure out a good way to handle this edge case that continues working for other cases.

**Comment by janko** [comment]
Sorry, this has slipped off my radar. Yeah, it makes sense to exclude `;` as well as the non-whitespace characters 👍🏻 I'll push a fix for this.

**Comment by azrazalea-debtbook** [comment]
Thank you so much for getting this in! Next round of dependency updates I'll be able to remove our workaround <3.
