### ISSUE TITLE
Compatibility with PDF::Reader

### ISSUE THREAD

**Issue by raivil** [janko/down#79]
Hi,
I'm working with the Shrine gem and uploading PFD files to S3 (direct upload).
During the upload, the code is adding some metadata such as the page count.

I noticed that PDF::Reader accepts IO objects as input, but it's not working with the `Down::ChunkedIO`class.

This is the code from the shrine uploader:

```
add_metadata do |file, metadata:, record:, **|
    case metadata["mime_type"]
    when "application/pdf"
      io = file.to_io if file.respond_to?(:to_io)
      reader = PDF::Reader.new(io)

      { page_count: reader.page_count }
```

Exception:
```
ArgumentError: input must be an IO-like object or a filename (Down::ChunkedIO)
```

Code from PDF::Reader that will try to read the IO object.
https://github.com/yob/pdf-reader/blob/625e8dca295d8b6a48f634cba812f14fd3b805a4/lib/pdf/reader/object_hash.rb#L601

Shouldn't the Down::ChunkedIO be considered and IO?

The come may work if it input a full file (file.download) or a StringIO, so there are alternatives there.

Any thoughts?
Thank you.

**Comment by janko** [comment]
Gems that want to support `Down::ChunkedIO` need to check whether the IO object responds to expected methods. `Down::ChunkedIO` cannot satisfy any of the conditions used by PDF::Reader (it cannot be a subclass of `IO`, `StringIO`, or `Tempfile`), so there is nothing that can be done in this library for it to be supported by PDF::Reader, the change needs to be made in that gem.

**Comment by janko** [comment]
As you said, you can download the file into a tempfile (via `file.download`) before passing it into PDF::Reader.
